In [1]:
import pandas as pd

In [2]:
train = pd.read_csv('../input/train.csv.zip')
test = pd.read_csv('../input/test.csv.zip')

In [3]:
train.shape, test.shape

((159571, 8), (153164, 2))

In [4]:
train.sample(9)

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
80426,d72e50f7d711d88e,"""\n\n Libya casualty report (French operations...",0,0,0,0,0,0
32169,5589256b4a233827,", yandman. You have to admit I really did, no ...",0,0,0,0,0,0
129111,b2848ce2ce314385,Just give me an example or two and I'll go aft...,0,0,0,0,0,0
90293,f1a426ce4e43052c,Thank you so much!!\nI'm very very glad to imp...,0,0,0,0,0,0
12790,21eb82d019478f78,Once again Ryulong proves that he's a fucking ...,1,0,1,0,1,1
120668,857adb63ce0ccb38,"Hi, Mishae!\nThanks a lot for the cordial welc...",0,0,0,0,0,0
90786,f2df9d90114e92f3,Thanks very much for taking the trouble! I'm f...,0,0,0,0,0,0
20708,36aac88b137487c9,You get what you pay for \n\nYou are eventual...,0,0,0,0,0,0
143041,fce3278f331f089b,Update: I have amended the links in the articl...,0,0,0,0,0,0

In [5]:
test.sample(9)

                      id                                       comment_text
66136   6e1a2ca3660e7749  I've left a reply on my talkpage  \n\n Suck eg...
152980  ffb2ac286df31e23  *My niggeez Auranor know 'sup. Neea know how 2...
112457  bbaa5f57fde7b763  Okay es-fucking- cog, who died and made you ki...
63571   69efeed39f07bf0e  == heidar abbasi == \n\n  \n\n سلام , علت پاک ...
108994  b5d50cb1324b1c23  " \n\n == deletion of my article.. == \n\n Hi ...
57257   5f3f5fdb847b76d6  " \n\n == File:SnowballGeography.gif listed fo...
39947   4251818febdb283e                     you people are fucking faggots
114080  be66caaa8b4746e1  " \n\n == Disagreement over the definition of ...
82870   8a3002195f21e9e0  hello boy sup BB oquv g gwbjgtf nonthinking jk...

In [6]:
train.mean(numeric_only=1).to_frame()

                      0
toxic          0.095844
severe_toxic   0.009996
obscene        0.052948
threat         0.002996
insult         0.049364
identity_hate  0.008805

In [7]:
train.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')

In [8]:
pd.crosstab(train.toxic, train.severe_toxic)

severe_toxic       0     1
toxic
0             144277     0
1              13699  1595

In [9]:
pd.crosstab(train.toxic, train.obscene)

obscene       0     1
toxic
0        143754   523
1          7368  7926

In [10]:
pd.crosstab(train.toxic, train.threat)

threat       0    1
toxic
0       144248   29
1        14845  449

In [11]:
pd.crosstab(train.toxic, train.insult)

insult       0     1
toxic
0       143744   533
1         7950  7344

In [12]:
pd.crosstab(train.toxic, train.identity_hate)

identity_hate       0     1
toxic
0              144174   103
1               13992  1302

In [13]:
train[['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']].corr()

,toxic,severe_toxic,obscene,threat,insult,identity_hate
toxic,1.000000,0.308619,0.676515,0.157058,0.647518,0.266009
severe_toxic,0.308619,1.000000,0.403014,0.123601,0.375807,0.201600
obscene,0.676515,0.403014,1.000000,0.141179,0.741272,0.286867
threat,0.157058,0.123601,0.141179,1.000000,0.150022,0.115128
insult,0.647518,0.375807,0.741272,0.150022,1.000000,0.337736
identity_hate,0.266009,0.201600,0.286867,0.115128,0.337736,1.000000

In [14]:
def split(s):
    return s.strip().split()

In [15]:
train.head().comment_text.map(split)

0    [Explanation, Why, the, edits, made, under, my...
1    [D'aww!, He, matches, this, background, colour...
2    [Hey, man,, I'm, really, not, trying, to, edit...
3    [", More, I, can't, make, any, real, suggestio...
4    [You,, sir,, are, my, hero., Any, chance, you,...
Name: comment_text, dtype: object

In [17]:
train.comment_text = train.comment_text.map(split)

In [18]:
toxic = train[train.toxic==1]
not_toxic = train[train.toxic==0]

In [19]:
toxic.sample(9)

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
58716,9d41c9574ed8811c,"[I, second, that., Superracist, shit,, as, if,...",1,0,0,0,0,0
153670,a08609ab5928ab1f,"[""::::::, I, got, blocked, for, 30, minutes,, ...",1,0,1,0,0,0
87562,ea372b8308012185,"[Stop, with, the, garbage, I'll, say, irreleva...",1,0,1,0,1,0
4796,0cb4cf1534acbf6f,"[My, dad, is, 6'7', you, dumb, snail, of, a, k...",1,0,0,0,0,0
8993,17ea9cbec8fd1ed5,"[AT, Have, you, bookmarked, ｗｗｗ．ＡｎｏｎＴａｌｋ．ｃｏｍ, ...",1,0,1,0,0,0
84898,e331202e74550d01,"[Ziggy, Sawdust, is, an, idiot, DON'T, DELETE,...",1,0,1,0,1,0
153682,a0cede3d652030d1,"["", """"Somebody,, go, write, one."""", Do, it, yo...",1,0,0,0,0,0
132785,c6709dc53840b5a3,"[again, again, again, this, is, not, going, to...",1,0,0,0,1,1
29354,4ddeff4d162f8358,"[Faggot, ==, Dude,, you, are, a, fucking, fagg...",1,1,1,0,1,1

In [20]:
not_toxic.sample(9)

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
156757,d317f23898261482,"[Where, as, I, wish, I, had, read, it, somewhe...",0,0,0,0,0,0
22137,3a614fb64738d8a5,"[You, have, truly, earned, your, namesake,, ha...",0,0,0,0,0,0
40184,6b42621e9e313654,"["", Denise, Oliver, What, about, her, roll, in...",0,0,0,0,0,0
116507,6ed0f2e91bdaddb0,"[Enough, Your, Nazi-ish, view, on, WP:BLP, is,...",0,0,0,0,0,0
41913,6fcfc212a8a4d8a1,"[Infobox, You, left, a, comment, at, the, info...",0,0,0,0,0,0
70238,bbe856fd4f6ab81f,"[Professions, Hi, Gavin,, the, article, is, a,...",0,0,0,0,0,0
150472,6ce0d0a0878852f6,"[About, St.Thomas, I, made, these, changes, fo...",0,0,0,0,0,0
75258,c94ef025c96a224d,"[No,, there, are, no, such, names.]",0,0,0,0,0,0
25251,42d649989f20b6b4,"[Oh,, well., Wouldn't, it, be, nice, if, the, ...",0,0,0,0,0,0

In [22]:
toxic.comment_text.sample(9).values

array([ list(['I', 'did', 'not', 'do', 'anything', 'wrong', 'Why', 'are', 'you', 'editing', 'Wikipedia?', 'Go', 'home', 'to', 'Armenia', 'and', 'shut', 'your', 'mouth.', 'you', 'lie', 'and', 'make', 'things', 'up.', 'Stop', 'now', 'your', 'PKK', 'vermin.']),
       list(['this', 'edit', 'was', 'posted', 'by', 'the', 'user', 'of', 'this', 'page,', 'you', 'all', 'really', 'think', 'you', 'can', 'make', 'me', 'not', 'edit', 'lol', 'you', 'all', 'are', 'funny', 'as', 'shit.', '206.217.197.164']),
       list(['FUCK', 'WIKIPEDIA', 'ON', 'WHEELS!', 'Fuck', 'off', 'wikipedia', 'you', 'fat', 'bastard', 'on', 'wheels', 'who', 'eats', 'your', 'own', 'shit!']),
       list(['And', 'what', 'will', 'happen', 'if', 'they', "don't", 'cease', 'immediately', 'oh', 'you', 'powerful', 'one?', 'Oh,', 'I', 'forgot,', 'you', 'said', 'block!!', 'HAHAHAHA', 'god,', 'you', 'are', 'really', 'stupid,', "aren't", 'you?', '-)', '09:33,', '31', 'Mar', '2005', '(UTC)']),
       list(['")', 'johnboywalton55', 'says', '""you\'re', 'a', 'spastic!!!""', 'also', '""Father', 'Daley,', 'reportedly', 'had', 'a', 'big', 'lump', 'on', 'the', 'side', 'of', 'his', 'head', 'in', 'the', 'shape', 'of', 'Connaught.""', '("']),
       list(['DCANDETO', 'SMELLS', 'FUNNY!', 'HE', 'IS', 'VERY', 'MEAN!']),
       list(['Tread', 'along', 'dear', 'boy', 'Goway', 'ya', 'fool', 'you', 'think', 'your', 'hard!']),
       list(['Fuck', 'you,', 'block', 'me,', 'you', 'faggot', 'pussy!']),
       list(['LAST', 'WARNING', 'YOU', 'FUCKING', 'TOSSER,', 'IT', 'TAKES', 'ME', '10', 'MINUTES', 'TO', 'RESOLVE', 'A', 'PAGE', 'SO', 'CUNTS', 'LIKE', 'YOU', 'CAN', 'FUCK', 'WIKIPEDIA', 'UP'])], dtype=object)